### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by KylePeterDavies** [moabukar/DevOps-Tooling#4]
Dear Moabukar, could I suggest `Terragrunt`, `Kubegrunt` and `Git-Xargs` all by Gruntworks, to whom I am not associated.

**Comment by moabukar** [comment]
> Dear Moabukar, could I suggest `Terragrunt`, `Kubegrunt` and `Git-Xargs` all by Gruntworks, to whom I am not associated.

Hey @KylePeterDavies - feel free to add it in, make a pull request and just follow the same template there:
[Tool](link) - can it be installed using Helm? if not, leave it empty, otherwise put the helm command>
